version: '3'

services:
  db:
    image: postgres
    container_name: db_app
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'


  app:
    build: .
    container_name: app_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env

volumes:
  postgres_data:
