# Generated by Django 4.2.6 on 2023-10-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_for_response', models.BigIntegerField(verbose_name='id с сайта')),
                ('answer', models.CharField(max_length=255, verbose_name='ответ')),
                ('question', models.TextField(verbose_name='вопрос')),
                ('created_at', models.DateTimeField(null=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
